version: '3'

services:
  ai-art-bot:
    image: ai-art-bot
    build: .
    volumes:
      - ./ideas.txt:/app/ideas.txt
      - huggingface:/root/.cache/huggingface
    env_file:
      - .env
    command: python3 app.py
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]

volumes:
  huggingface: